#!/usr/bin/env python3
"""Add Phase 2 vendors (Observability, Storage, Catalog, ETL/ELT) to database."""

import json
from pathlib import Path

# Remaining 20 vendors to add
PHASE2_REMAINING_VENDORS = [
    # Observability Platforms (5)
    {
        "id": "datadog",
        "name": "Datadog",
        "category": "Observability Platform",
        "description": "Unified observability platform with infrastructure monitoring, APM, log management, and Cloud SIEM. Real-time threat detection with AI-powered security monitoring and DevSecOps integration.",
        "website": "https://www.datadoghq.com",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": True,
            "multi_engine_query": False,
            "open_table_format": "proprietary",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": True,
            "team_size_required": "standard",
            "cost_model": "subscription",
            "cost_predictability": "medium",
            "siem_integration": False,
            "compliance_certifications": ["SOC2", "ISO27001", "FedRAMP"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$19K-1.2M annually",
        "cost_notes": "Pro: $15/host/month. Enterprise: $23/host/month. DevSecOps Pro: $22/host/month. DevSecOps Enterprise: $34/host/month. Multi-dimensional usage-based pricing.",
        "evidence_source": "Datadog pricing 2025, UnderDefense guide, Vendr marketplace",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["cloud-siem", "apm", "infrastructure-monitoring", "ai-powered", "devsecops"]
    },
    {
        "id": "new-relic",
        "name": "New Relic One",
        "category": "Observability Platform",
        "description": "Full-stack observability platform with APM, infrastructure monitoring, and digital experience monitoring. 100GB free data ingest with 780+ integrations and AIOps capabilities.",
        "website": "https://newrelic.com",
        "capabilities": {
            "sql_interface": True,
            "streaming_query": True,
            "multi_engine_query": False,
            "open_table_format": "proprietary",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "standard",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "ISO27001"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$30K-300K annually",
        "cost_notes": "$0.30/GB data ingest (100GB free). Core users: $49/user/month. Full platform users: $99/user/month (Standard tier). Data Plus: $0.50/GB with extended retention.",
        "evidence_source": "New Relic pricing 2025, CloudZero guide, SigNoz comparison",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["full-stack", "aiops", "rum", "usage-based-pricing", "free-tier"]
    },
    {
        "id": "dynatrace",
        "name": "Dynatrace",
        "category": "Observability Platform",
        "description": "AI-powered observability platform with Davis hypermodal AI engine. 3rd generation platform with Grail data lakehouse and autonomous intelligence. Enterprise-grade with AI observability for GenAI.",
        "website": "https://www.dynatrace.com",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": True,
            "multi_engine_query": False,
            "open_table_format": "proprietary",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": True,
            "team_size_required": "standard",
            "cost_model": "consumption",
            "cost_predictability": "medium",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "ISO27001", "FedRAMP"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$100K-1M+ annually",
        "cost_notes": "Consumption-based pricing with volume discounts. Premium enterprise pricing. Custom quotes through sales. AI observability for LLM monitoring included.",
        "evidence_source": "Dynatrace pricing 2025, TechRadar review, State of Observability 2025",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["ai-powered", "davis-ai", "grail", "llm-observability", "enterprise"]
    },
    {
        "id": "splunk-observability",
        "name": "Splunk Observability Cloud",
        "category": "Observability Platform",
        "description": "Cloud-native observability suite with APM, infrastructure monitoring, RUM, and synthetic monitoring. Pre-built dashboards, AI Assistant, and intelligent problem detection.",
        "website": "https://www.splunk.com/en_us/products/observability-cloud.html",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": True,
            "multi_engine_query": False,
            "open_table_format": "proprietary",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": True,
            "team_size_required": "standard",
            "cost_model": "subscription",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "ISO27001", "FedRAMP"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$60K-600K annually",
        "cost_notes": "Infrastructure: $15/host/month. Apps + Infra: $60/host/month. End-to-End: $75/host/month. Standard discounts 28-48% (real cost: $60K-$84K for 200 hosts end-to-end).",
        "evidence_source": "Splunk Observability pricing 2025, Vendr marketplace, TrustRadius",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["cloud-native", "ai-assistant", "rum", "synthetic-monitoring", "transparent-pricing"]
    },
    {
        "id": "honeycomb",
        "name": "Honeycomb",
        "category": "Observability Platform",
        "description": "Developer-first observability with distributed tracing and BubbleUp anomaly detection. AI-native suite (Honeycomb Intelligence) with event-based pricing. Native OpenTelemetry support.",
        "website": "https://www.honeycomb.io",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": True,
            "multi_engine_query": False,
            "open_table_format": "proprietary",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "lean",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": False,
            "compliance_certifications": ["SOC2"],
            "data_governance": False,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "medium",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$15K-200K annually",
        "cost_notes": "Event-based pricing: Free (20M events/month). Pro: $130/month (100M events). Scales to 1.5B events. Unlimited users and services. Honeycomb Intelligence AI included free.",
        "evidence_source": "Honeycomb pricing 2025, G2 reviews, CTO Club review",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["developer-first", "distributed-tracing", "opentelemetry", "ai-native", "event-based-pricing"]
    },
    # Object Storage (5)
    {
        "id": "amazon-s3",
        "name": "Amazon S3",
        "category": "Object Storage",
        "description": "Industry-leading cloud object storage with 99.999999999% durability. Foundation for data lakes with seamless integration to Athena, EMR, Redshift Spectrum. Multiple storage classes for cost optimization.",
        "website": "https://aws.amazon.com/s3",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "iceberg-native",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": False,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "lean",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "FedRAMP", "ISO27001", "HIPAA"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": False,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$10K-500K storage costs",
        "cost_notes": "Standard: $0.023/GB/month (first 50TB). Glacier: $0.004/GB/month. Intelligent-Tiering auto-optimizes. New users: $200 free credits (6 months, July 2025+).",
        "evidence_source": "AWS S3 pricing 2025, nOps guide, CloudChipr analysis",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["aws-native", "data-lake-foundation", "11-nines-durability", "intelligent-tiering"]
    },
    {
        "id": "azure-blob-storage",
        "name": "Azure Blob Storage",
        "category": "Object Storage",
        "description": "Massively scalable object storage for unstructured data with 99.999999999% durability. SFTP support, hot/cool/cold/archive tiers, and Reserved Capacity discounts.",
        "website": "https://azure.microsoft.com/en-us/services/storage/blobs",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "delta",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": False,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "lean",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "ISO27001", "HIPAA"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": False,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$8K-400K storage costs",
        "cost_notes": "Hot: $0.018/GB/month (first 50TB). Cool: $0.01/GB/month. Cold: $0.0036/GB/month. Archive: $0.00099/GB/month. Reserved Capacity discounts available.",
        "evidence_source": "Azure Blob Storage pricing 2025, CloudZero breakdown, CloudChipr guide",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["azure-native", "sftp-support", "11-nines-durability", "tiered-storage"]
    },
    {
        "id": "google-cloud-storage",
        "name": "Google Cloud Storage",
        "category": "Object Storage",
        "description": "Scalable object storage with Standard, Nearline, Coldline, Archive classes. Low-latency workloads with encryption at rest/transit, IAM, and object versioning. BigQuery and Vertex AI integration.",
        "website": "https://cloud.google.com/storage",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "iceberg-support",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": False,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "lean",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "ISO27001", "HIPAA"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$10K-450K storage costs",
        "cost_notes": "Standard: $0.020/GB/month. Nearline: $0.010/GB/month. Coldline: $0.004/GB/month. Archive: $0.0012/GB/month. $300 trial credits for new users.",
        "evidence_source": "Google Cloud Storage pricing 2025, Elite Cloud guide, TechAnnouncer 2025",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["gcp-native", "multi-class-storage", "bigquery-integration", "vertex-ai-ready"]
    },
    {
        "id": "minio",
        "name": "MinIO",
        "category": "Object Storage",
        "description": "High-performance S3-compatible object storage for AI/ML and analytics. Multi-gigabit throughput per node with native Kubernetes deployment. Most widely tested S3 alternative (tens of thousands of users).",
        "website": "https://min.io",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "iceberg-native",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid", "edge"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": False,
            "team_size_required": "standard",
            "cost_model": "open-source",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": [],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "community",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$30K-300K infrastructure costs",
        "cost_notes": "Open source (AGPL v3). Infrastructure-only costs. Enterprise Edition available. Full S3 API compatibility. Exabyte-scale deployments with sub-10ms latency.",
        "evidence_source": "MinIO documentation 2025, min.io, S3 Compatible Storage Benchmark",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["oss", "s3-compatible", "kubernetes-native", "ai-optimized", "edge-ready"]
    },
    {
        "id": "ceph",
        "name": "Ceph Object Storage (RGW)",
        "category": "Object Storage",
        "description": "Open-source distributed storage with S3 API compatibility. 111 GiB/s GET throughput achieved (2025 benchmarks). Storage tiering with cloud integration and no single point of failure.",
        "website": "https://ceph.io",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid"],
            "cloud_native": False,
            "multi_cloud": True,
            "operational_complexity": "high",
            "managed_service_available": False,
            "team_size_required": "large",
            "cost_model": "open-source",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": [],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "community",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": False,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$50K-400K infrastructure costs",
        "cost_notes": "Open source (LGPL). Infrastructure-only. 3× throughput increase (4→12 nodes). Storage tiering to cloud. Exabyte-scale capability. Commercial support from Red Hat/Mirantis.",
        "evidence_source": "Ceph benchmarking 2025, ceph.io, Ubuntu Ceph guide",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["oss", "s3-compatible", "distributed-storage", "exabyte-scale", "storage-tiering"]
    },
    # Data Catalog & Governance (5)
    {
        "id": "apache-atlas",
        "name": "Apache Atlas",
        "category": "Data Catalog & Governance",
        "description": "Open metadata management and governance for Hadoop and beyond. Data classification, lineage tracking, business glossary, and Apache Ranger integration for RBAC/ABAC security.",
        "website": "https://atlas.apache.org",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid"],
            "cloud_native": False,
            "multi_cloud": True,
            "operational_complexity": "high",
            "managed_service_available": False,
            "team_size_required": "large",
            "cost_model": "open-source",
            "cost_predictability": "high",
            "siem_integration": False,
            "compliance_certifications": [],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "community",
            "community_size": "medium",
            "ocsf_support": False,
            "ml_analytics": False,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$50K-300K infrastructure costs",
        "cost_notes": "Open source (Apache License). Infrastructure-only. Complex deployment. Hadoop-optimized but supports multi-platform. Ranger integration for fine-grained access control.",
        "evidence_source": "Apache Atlas documentation, Atlan guide 2025, Secoda introduction",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["oss", "hadoop-native", "data-lineage", "business-glossary", "ranger-integration"]
    },
    {
        "id": "collibra",
        "name": "Collibra Data Intelligence",
        "category": "Data Catalog & Governance",
        "description": "Unified data catalog, governance, quality, and AI governance platform. Gartner Magic Quadrant Leader 2025. Data lineage, GDPR/HIPAA compliance, and centralized policy management.",
        "website": "https://www.collibra.com",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": True,
            "team_size_required": "standard",
            "cost_model": "subscription",
            "cost_predictability": "medium",
            "siem_integration": False,
            "compliance_certifications": ["SOC2", "ISO27001"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$170K-510K annually",
        "cost_notes": "$170K (12-month), $340K (24-month), $510K (36-month) yearly subscription. Base licensing ~30-50% of total (connectors/users extra). Gartner Leader 2025.",
        "evidence_source": "Collibra pricing 2025, data.world analysis, SelectHub review",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["gartner-leader", "ai-governance", "enterprise", "compliance-focused", "premium-pricing"]
    },
    {
        "id": "alation",
        "name": "Alation Data Intelligence Platform",
        "category": "Data Catalog & Governance",
        "description": "Agentic data intelligence platform with 120+ connectors. AI-powered documentation, policy enforcement, and data product delivery. Pioneer in modern data catalog (founded 2012).",
        "website": "https://www.alation.com",
        "capabilities": {
            "sql_interface": True,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": True,
            "team_size_required": "standard",
            "cost_model": "subscription",
            "cost_predictability": "medium",
            "siem_integration": False,
            "compliance_certifications": ["SOC2", "ISO27001"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$198K-500K annually",
        "cost_notes": "Starting ~$20K annually (entry). Enterprise ~$198K/year. Asset-based pricing model (2025). Complex pricing with hidden costs noted by users.",
        "evidence_source": "Alation pricing 2025, Atlan comparison, SelectHub review",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["agentic-workflows", "ai-powered", "120-connectors", "catalog-pioneer", "enterprise"]
    },
    {
        "id": "aws-glue",
        "name": "AWS Glue Data Catalog",
        "category": "Data Catalog & Governance",
        "description": "Serverless metadata catalog and ETL service. First 1M metadata objects free. Schema Registry with Apache Avro support. Lake Formation integration for unified governance.",
        "website": "https://aws.amazon.com/glue",
        "capabilities": {
            "sql_interface": True,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "iceberg-native",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": False,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "lean",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "FedRAMP", "ISO27001", "HIPAA"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$10K-150K annually",
        "cost_notes": "First 1M objects free. $1 per 100K objects/month beyond. Crawlers: $0.44/DPU-hour (10min minimum). Schema Registry included free. Lake Formation no separate charge.",
        "evidence_source": "AWS Glue pricing 2025, CloudChipr breakdown, Hevo Data guide",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["aws-native", "serverless", "generous-free-tier", "schema-registry", "lake-formation"]
    },
    {
        "id": "microsoft-purview",
        "name": "Microsoft Purview Data Governance",
        "category": "Data Catalog & Governance",
        "description": "Unified data governance with pay-as-you-go pricing (January 2025 model). Governed assets and DGPU-based data health management. No cost for scanning, charge only for governance.",
        "website": "https://azure.microsoft.com/en-us/services/purview",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": True,
            "team_size_required": "standard",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": False,
            "compliance_certifications": ["SOC2", "ISO27001", "HIPAA"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": False,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$20K-200K annually",
        "cost_notes": "New model (Jan 6, 2025): Pay for governed assets only (no scan cost). 200 governed assets example: $100/month (30 days). DGPU: 60min compute unit for data quality.",
        "evidence_source": "Microsoft Purview pricing 2025, Erwin de Kreuk analysis, Azure documentation",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["azure-native", "pay-as-you-go", "governed-assets", "dgpu-model", "2025-pricing"]
    },
    # ETL/ELT Platforms (5)
    {
        "id": "apache-nifi",
        "name": "Apache NiFi",
        "category": "ETL/ELT Platform",
        "description": "Real-time dataflow automation with drag-and-drop UI. Low-code data integration for ETL processes with data provenance tracking. Cloud-agnostic with improved performance for AI streaming (2025).",
        "website": "https://nifi.apache.org",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": True,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid"],
            "cloud_native": False,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": False,
            "team_size_required": "standard",
            "cost_model": "open-source",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": [],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "community",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": False,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$40K-250K infrastructure costs",
        "cost_notes": "Open source (Apache License). Infrastructure-only. Real-time low-code advantage over Airflow. Cloud-agnostic. Job market value strong for 2025.",
        "evidence_source": "Apache NiFi documentation, Refonte Learning 2025, DataCamp comparison",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["oss", "real-time-etl", "low-code", "drag-and-drop", "data-provenance"]
    },
    {
        "id": "airbyte",
        "name": "Airbyte",
        "category": "ETL/ELT Platform",
        "description": "Open-source ELT platform with 600+ connectors and AI-assisted builder. Capacity-based pricing with free self-hosted option. Cloud, self-hosted, and Enterprise (BYOC) deployment.",
        "website": "https://airbyte.com",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "lean",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": ["SOC2"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$6K-100K annually",
        "cost_notes": "Free OSS self-hosted. Cloud: Capacity-based (Data Workers, not volume). Mid-market: $500-5K/month. Enterprise: $50K+/year. 600+ connectors included.",
        "evidence_source": "Airbyte pricing 2025, Vendr marketplace, Sider.ai review",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["oss", "600-connectors", "ai-assisted", "capacity-based-pricing", "free-tier"]
    },
    {
        "id": "fivetran",
        "name": "Fivetran",
        "category": "ETL/ELT Platform",
        "description": "Automated data pipelines with 700+ connectors. Monthly Active Rows (MAR) pricing per connector. Zero-maintenance architecture with real-time syncing every few minutes.",
        "website": "https://www.fivetran.com",
        "capabilities": {
            "sql_interface": False,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "lean",
            "cost_model": "subscription",
            "cost_predictability": "medium",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "ISO27001", "HIPAA"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": False,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$25K-200K annually",
        "cost_notes": "MAR pricing per connector (March 2025 change). $25K-200K annually typical. Free, Standard, Enterprise, Business Critical tiers. Bulk discounts removed March 2025.",
        "evidence_source": "Fivetran pricing 2025, 5X comparison, Windsor.ai analysis",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["700-connectors", "zero-maintenance", "real-time-sync", "mar-pricing", "automated"]
    },
    {
        "id": "talend",
        "name": "Qlik Talend Cloud",
        "category": "ETL/ELT Platform",
        "description": "Unified data integration, quality, and governance with 1000+ connectors. AI transformation assistant with natural language to SQL. Four editions with capacity-based usage metering.",
        "website": "https://www.talend.com",
        "capabilities": {
            "sql_interface": True,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "multiple",
            "schema_evolution": True,
            "deployment_models": ["cloud", "on-prem", "hybrid"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "medium",
            "managed_service_available": True,
            "team_size_required": "standard",
            "cost_model": "subscription",
            "cost_predictability": "medium",
            "siem_integration": True,
            "compliance_certifications": ["SOC2", "ISO27001"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "large",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$50K-500K annually",
        "cost_notes": "Four editions with capacity-based usage (data volume + job executions + duration). $50K-500K+ annually. OSS version free. Custom quotes required.",
        "evidence_source": "Talend pricing 2025, Mammoth.io analysis, AWS Marketplace",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["1000-connectors", "ai-transformation", "qlik-integration", "enterprise", "capacity-based"]
    },
    {
        "id": "matillion",
        "name": "Matillion Data Productivity Cloud",
        "category": "ETL/ELT Platform",
        "description": "Cloud-native ELT for Snowflake, Redshift, BigQuery, Synapse. Maia AI virtual data engineers (2025). Unlimited users/environments with consumption-based pricing. 271% ROI potential.",
        "website": "https://www.matillion.com",
        "capabilities": {
            "sql_interface": True,
            "streaming_query": False,
            "multi_engine_query": True,
            "open_table_format": "iceberg-support",
            "schema_evolution": True,
            "deployment_models": ["cloud"],
            "cloud_native": True,
            "multi_cloud": True,
            "operational_complexity": "low",
            "managed_service_available": True,
            "team_size_required": "lean",
            "cost_model": "consumption",
            "cost_predictability": "high",
            "siem_integration": True,
            "compliance_certifications": ["SOC2"],
            "data_governance": True,
            "maturity": "production",
            "vendor_support": "enterprise",
            "community_size": "medium",
            "ocsf_support": False,
            "ml_analytics": True,
            "api_extensibility": True
        },
        "typical_annual_cost_range": "$12K-50K annually",
        "cost_notes": "Basic: $1K/month. Advanced: $2K/month. Enterprise tier available. Free plan with limited features. Consumption-based with 271% ROI. Unlimited users/environments/scale.",
        "evidence_source": "Matillion pricing 2025, SaaSworthy analysis, Matillion ROI study",
        "last_updated": "2025-10-16T00:00:00",
        "validated_by": "Jeremy Wiley",
        "tags": ["cloud-native-elt", "maia-ai", "snowflake-native", "unlimited-users", "271-roi"]
    }
]

def main():
    """Add Phase 2 remaining vendors to database."""
    db_path = Path(__file__).parent.parent / "data" / "vendor_database.json"

    with open(db_path, 'r') as f:
        data = json.load(f)

    current_count = len(data['vendors'])
    print(f"Current vendor count: {current_count}")

    # Add new vendors
    data['vendors'].extend(PHASE2_REMAINING_VENDORS)
    data['total_vendors'] = len(data['vendors'])
    data['last_full_update'] = "2025-10-16T00:00:00"

    # Write back
    with open(db_path, 'w') as f:
        json.dump(data, f, indent=2)

    print(f"✓ Added {len(PHASE2_REMAINING_VENDORS)} vendors")
    print(f"✓ Total vendors now: {data['total_vendors']}")
    print(f"✓ Database updated: {db_path}")

if __name__ == "__main__":
    main()
